---

service: SampleDataPartitioner

plugins:
  - serverless-plugin-existing-s3

custom:
  bucketName: ""
  sourcePrefix: sample_data_firehose
  targetPrefix: sample_data
  database: default
  table: sample_data

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10

  stage: ${opt:stage, 'dev'}
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:ListBucket"
        - "s3:ListBucketVersions"
        - "s3:ListObjects"
        - "s3:ListObjectsV2"
        - "s3:GetObject"
        - "s3:GetObjectVersion"
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucketName}"
        - "arn:aws:s3:::${self:custom.bucketName}/*"
    - Effect: Allow
      Action:
        - "athena:StartQueryExecution"
      Resource:
        - "*"

  environment:
    NODE_ENV: ${self:provider.stage}
    BUCKET_NAME: ${self:custom.bucketName}
    TARGET_PREFIX: ${self:custom.targetPrefix}
    DATABASE: ${self:custom.database}
    TABLE: ${self:custom.table}

functions:
  main:
    handler: src/handler.main
    events:
      - existingS3:
          bucket: ${self:custom.bucketName}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.sourcePrefix}/
