Description: "Create firehose for realtime data collection"

Parameters:
  FirehoseName:
    Description: Firehose Delivery Stream Name.
    Type: String
    Default: sample-data-collection

  FirehoseToS3Prefix:
    Description: S3 prefix for Firehose to deliver data to S3.
    Type: String
    Default: sample_data_firehose/

  FirehoseTableName:
    Description: Table name of the firehose imported data.
    Type: String
    Default: sample_data_firehose

  DataTableS3Prefix:
    Description: S3 prefix for re-partitioned data.
    Type: String
    Default: sample_data_firehose

  DataTableName:
    Description: Table name of the re-partitioned data.
    Type: String
    Default: sample_data

  DatabaseName:
    Description: Glue database name to store the glue tables.
    Type: String
    Default: default

  BucketName:
    Description: S3 bucket name for storing the collected data.
    Type: String

Resources:
  DataTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref DatabaseName
      TableInput:
        Name: !Ref DataTableName
        Owner: owner
        Retention: 0
        TableType: EXTERNAL_TABLE
        Parameters:
          compressionType: none
          classification: parquet
        StorageDescriptor:
          StoredAsSubDirectories: false
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          BucketColumns: []
          NumberOfBuckets: -1
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
            Parameters:
              "serialization.format": "1"
          Compressed: false
          Location: !Sub "s3://${BucketName}/${DataTableS3Prefix}"
          Columns:
            - Name: ts
              Type: bigint
              Comment: UNIX timestamp in milliseconds of the event
            - Name: uid
              Type: string
              Comment: Unique identifier of the user
            - Name: category
              Type: string
              Comment: Event group name
            - Name: action
              Type: string
              Comment: Event interaction type
            - Name: label
              Type: string
              Comment: Additional information of the event
        PartitionKeys:
          - Name: partition_data
            Type: string
          - Name: partition_hour
            Type: string

  FirehoseTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref DatabaseName
      TableInput:
        Name: !Ref FirehoseTableName
        Owner: owner
        Retention: 0
        TableType: EXTERNAL_TABLE
        Parameters:
          compressionType: none
          classification: parquet
        StorageDescriptor:
          StoredAsSubDirectories: false
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          BucketColumns: []
          NumberOfBuckets: -1
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
            Parameters:
              "serialization.format": "1"
          Compressed: false
          Location: !Sub "s3://${BucketName}/${FirehoseToS3Prefix}"
          Columns:
            - Name: ts
              Type: bigint
              Comment: UNIX timestamp in milliseconds of the event
            - Name: uid
              Type: string
              Comment: Unique identifier of the user
            - Name: category
              Type: string
              Comment: Event group name
            - Name: action
              Type: string
              Comment: Event interaction type
            - Name: label
              Type: string
              Comment: Additional information of the event
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
          - Name: hour
            Type: string

  FirehoseDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${FirehoseName}-firehose"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref "AWS::AccountId"
      Policies:
        - PolicyName: "FirehoseAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "glue:GetTableVersions"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: "Allow"
                Action: "logs:PutLogEvents"
                Resource: !GetAtt FirehoseLogGroup.Arn

  FirehoseLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/kinesisfirehose/${FirehoseName}"

  FirehoseS3DeliveryLogStream:
    Type: "AWS::Logs::LogStream"
    DependsOn: FirehoseLogGroup
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: S3Delivery

  Firehose:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamName: !Ref FirehoseName
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::${BucketName}"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 64
        CompressionFormat: UNCOMPRESSED # Necessary for data format conversion
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: S3Delivery
        Prefix: !Ref FirehoseToS3Prefix
        RoleARN: !GetAtt FirehoseDeliveryRole.Arn
